### ISSUE TITLE
Good work and a little idea

### ISSUE THREAD

**Issue by emilen72** [ifilot/p2000t-sdcard#12]
Can you think to be possible to port this projet to use the pi pico rp2040, the purple clone with 16MB on board and make a multicart or a .cas loader from it? it would be very cheap :-) and easy to build (the hardware assembly of course)

it's already been done for atari 800 and othe console... some links that maybe you know... 
https://forums.atariage.com/topic/351546-a8picocart-unocart-on-a-raspberry-pi-pico/
https://github.com/robinhedwards/A8PicoCart
https://github.com/aotta/PiCOLECO
https://github.com/aotta/SD-1000
https://github.com/aotta/PiRTOII

only a little idea :-)

best regards
Emiliano

**Comment by ifilot** [comment]
This is indeed a nice suggestion and I have been pondering about this myself in the past. Two things held me back, the Raspberry Pi PICO has fewer pins than I would like and these pins operate at 3.3V, not 5.0V. Now there are a number of posts out there that suggest that the PICO is 5.0V tolerant with exception of the ADC pins, but so far I have not dared to put that to the test. All my projects involving the PICO use level-shifting.

I reckon porting this project to the PICO is certainly possible, essentially encoding what I have now put in hardware into software. It is something I might do in the future, but right now I have already enough projects on my hands and I would rather complete the ones I have now than starting new ones.

I do appreciate the list of links you have provided. If (when) I am going to adopt this endeavor, this will nicely kick-start the project.
